name: search_textfield
description: "A customizable Flutter widget that provides a search text field with dropdown suggestions. Shows live search results in a dropdown menu as users type."
version: 0.0.2
homepage: https://github.com/hangpuan/search_textfield

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:


